# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' lovain modularity
#' @export
#' 
RunModularityClusteringCpp <- function(SNN, modularityFunction, resolution, algorithm, nRandomStarts, nIterations, randomSeed, printOutput) {
    .Call('_scMRMA_RunModularityClusteringCpp', PACKAGE = 'scMRMA', SNN, modularityFunction, resolution, algorithm, nRandomStarts, nIterations, randomSeed, printOutput)
}

#' SNN matrix
#' @export
#'
getSNN <- function(knnMatrix, prune) {
    .Call('_scMRMA_getSNN', PACKAGE = 'scMRMA', knnMatrix, prune)
}

#' normalize single cell count data
#' @param data count data
#' @export
#' 
LogNorm <- function(data, display_progress = FALSE) {
    .Call('_scMRMA_LogNorm', PACKAGE = 'scMRMA', data, display_progress)
}

#' variance calculation
#' @export
#' 
SparseRowVar2 <- function(mat, mu, display_progress = FALSE) {
    .Call('_scMRMA_SparseRowVar2', PACKAGE = 'scMRMA', mat, mu, display_progress)
}

#' variance calculation
#' @export
#' 
SparseRowVarStd <- function(mat, mu, sd, vmax, display_progress = FALSE) {
    .Call('_scMRMA_SparseRowVarStd', PACKAGE = 'scMRMA', mat, mu, sd, vmax, display_progress)
}

