# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

RunModularityClusteringCpp <- function(SNN, modularityFunction, resolution, algorithm, nRandomStarts, nIterations, randomSeed, printOutput) {
    .Call('_scMRMA_RunModularityClusteringCpp', PACKAGE = 'scMRMA', SNN, modularityFunction, resolution, algorithm, nRandomStarts, nIterations, randomSeed, printOutput)
}

getSNN <- function(knnMatrix, prune) {
    .Call('_scMRMA_getSNN', PACKAGE = 'scMRMA', knnMatrix, prune)
}

getSNN2 <- function(knnMatrix, prune) {
    .Call('_scMRMA_getSNN2', PACKAGE = 'scMRMA', knnMatrix, prune)
}

LogNorm <- function(data, display_progress = FALSE) {
    .Call('_scMRMA_LogNorm', PACKAGE = 'scMRMA', data, display_progress)
}

SparseRowVar2 <- function(mat, mu, display_progress = FALSE) {
    .Call('_scMRMA_SparseRowVar2', PACKAGE = 'scMRMA', mat, mu, display_progress)
}

SparseRowVarStd <- function(mat, mu, sd, vmax, display_progress = FALSE) {
    .Call('_scMRMA_SparseRowVarStd', PACKAGE = 'scMRMA', mat, mu, sd, vmax, display_progress)
}

